In [9]:
import numpy as np
print(np.__version__)


2.3.2


In [10]:
# 1D array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [12]:
# 2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [13]:
# 3D array
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [15]:
# Zero Dimensions
a = np.array([42])
print(a)

[42]


In [59]:
arr = np.array([1, 2, 3, 4], ndmin=6) 
print(arr) 
print('number of dimensions :', arr.ndim)

[[[[[[1 2 3 4]]]]]]
number of dimensions : 6


In [3]:
from numpy import *
a = array([101,102,103,104,105])   
len(a)
print(a)

[101 102 103 104 105]


In [5]:
for i in a:
    print(a)

[101 102 103 104 105]
[101 102 103 104 105]
[101 102 103 104 105]
[101 102 103 104 105]
[101 102 103 104 105]


In [6]:
l = [1,2,3,4]
print(len(l))
print(l)

4
[1, 2, 3, 4]


In [7]:
n=len(a)
i=0
while i<n:
    print(i,a[i])
    i+=1

0 101
1 102
2 103
3 104
4 105


In [8]:
import numpy as np 
arr = np.array([1, 2, 3, 4])
print(arr[2]) 

3


In [9]:
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [10]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]]) 
print(arr)
print('2nd element on 1st row: ', arr[0, 3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  4


In [30]:
import numpy as np
np.linspace(1,10.5,dtype=int,endpoint=False,retstep=True)


(array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  4,
         4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,  7,
         7,  7,  7,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10, 10]),
 np.float64(0.19))

In [31]:
a = np.linspace(1,7,9)
print(a)

[1.   1.75 2.5  3.25 4.   4.75 5.5  6.25 7.  ]


In [32]:
for i in a:
    print(i)

1.0
1.75
2.5
3.25
4.0
4.75
5.5
6.25
7.0


In [40]:
a = np.array([0,30,45,60,90],dtype = int)
print(a)
sin = np.sin(a)
cos = np.cos(a)
tan = np.tan(a)
# cot = np.cot(a)
# cosec = np.cosec(a)
# sec = np.sec(a)
print(sin)
print(cos)
print(tan)
# print(cot)
# print(cosec)
# print(sec)

[ 0 30 45 60 90]
[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]


In [6]:
import numpy as np
a = np.linspace(1,9,dtype=int,retstep=True,endpoint=False)
print(a)

(array([1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4,
       4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7,
       8, 8, 8, 8, 8, 8]), np.float64(0.16))


In [4]:
import numpy as np
a=np.linspace(1,7,9)
print(a)

[1.   1.75 2.5  3.25 4.   4.75 5.5  6.25 7.  ]


In [11]:
a=np.logspace(1,4,7,base=10,endpoint=True)
print(a)

[   10.            31.6227766    100.           316.22776602
  1000.          3162.27766017 10000.        ]


In [13]:
a = np.logspace(1,4,num=7,base=3,endpoint=False)
print(a)

[ 3.          4.80398666  7.6927626  12.31864296 19.7261988  31.58813194
 50.58298812]


In [14]:
a=np.logspace(1,7,9)
for i in a:
    print(i)

10.0
56.23413251903491
316.22776601683796
1778.2794100389228
10000.0
56234.13251903491
316227.7660168379
1778279.410038923
10000000.0


In [15]:
import numpy as np
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [16]:
a = np.arange(5,9)
print(a)

[5 6 7 8]


In [17]:
a=np.arange(5,10,3)
print(a)

[5 8]


In [19]:
a=np.arange(0,3,6)
print(a)

[0]


In [20]:
a=np.arange(0,11,3)
print(a)

[0 3 6 9]


In [22]:
a=np.arange(0,30,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [23]:
a=np.arange(1,7,3)
for i in a:
    print(i)

1
4


In [25]:
a=np.zeros((3,3),dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [26]:
np.zeros(3)

array([0., 0., 0.])

In [40]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
a = np.zeros(5)
b = np.zeros(5,dtype=int)
c = np.zeros((3,2))
print(a,b,c)

[0. 0. 0. 0. 0.] [0 0 0 0 0] [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [45]:
a=np.zeros(5)
print(a[0])
print(a[1])

0.0
0.0


In [46]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.ones(3)

array([1., 1., 1.])

In [49]:
a=np.ones((3,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [54]:
a=np.ones(5)
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])

1.0
1.0
1.0
1.0
1.0


In [55]:
y=np.empty(5)
print(y)

[1. 1. 1. 1. 1.]


In [56]:
y=np.ones(4)
print(y)

[1. 1. 1. 1.]


In [58]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
np.eye(4,4)
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])